catalog
catalogDescription

	^ 'XMLParser provides validating SAX and DOM parsers for well-formed XML documents on Pharo, Squeak, and Gemstone. It also provides a DOM API for manipulating documents, namespace support, and an optional XMLWriter for writing documents. Validation and namespace checking are enabled by default, but not resolution of external entities.

Implements:
	http://www.w3.org/TR/REC-xml/
	http://www.w3.org/TR/REC-xml-names/
	http://www.w3.org/TR/xml-id/
	http://www.w3.org/TR/xmlbase/
	https://www.w3.org/TR/xml-c14n
'