initialization
initialize
	super initialize.

	xmlDeclarationColor := DefaultSecondaryMarkupColor.
	doctypeDeclarationColor := DefaultSecondaryMarkupColor.
	piColor := DefaultSecondaryMarkupColor.

	declarationColor := DefaultPrimaryMarkupColor.
	tagColor := DefaultPrimaryMarkupColor.

	quotedStringValueColor := DefaultQuotedStringValueColor.
	entityReferenceColor := DefaultEntityReferenceColor.
	commentColor := DefaultCommentColor.
	cdataColor := DefaultCDataColor.