class initialization
initialize
	"self initialize"

	DefaultPrimaryMarkupColor := TextColor color: Color purple.
	DefaultSecondaryMarkupColor := TextColor color: Color blue.
	DefaultQuotedStringValueColor := TextColor color: Color red.
	DefaultEntityReferenceColor := TextColor color: Color magenta.
	DefaultCommentColor := TextColor color: Color gray.
	DefaultCDataColor := TextColor color: Color veryDarkGray.