SystemOrganization addCategory: #'XML-Tests-Parser'!
SystemOrganization addCategory: 'XML-Tests-Parser-DOM'!
SystemOrganization addCategory: 'XML-Tests-Parser-DTD'!
SystemOrganization addCategory: 'XML-Tests-Parser-Factories'!
SystemOrganization addCategory: 'XML-Tests-Parser-Namespaces'!
SystemOrganization addCategory: 'XML-Tests-Parser-Streams'!
SystemOrganization addCategory: 'XML-Tests-Parser-URI'!
SystemOrganization addCategory: 'XML-Tests-Parser-Utils'!
